-- ============================================================================
-- The Prairie Dispatch network — shared content database schema (Postgres).
--
-- GENERATED by tools/schema-sql.php from app/db.php (pp_schema_ddl).
-- Do not hand-edit; regenerate with:  php tools/schema-sql.php --write
--
-- Standalone bootstrap for schema version 19. Equivalent to running
--   php tools/migrate.php --apply
-- against an empty target. The application does NOT install anything on
-- first connection — an unprepared database answers 503 until the
-- migration runner (or this file) has prepared it.
--
-- Runs in the app's own namespace; adjust the schema name to taste.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS prairiedispatch;
SET search_path TO prairiedispatch;

CREATE TABLE sites (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(160) NOT NULL,
            slug VARCHAR(191) NOT NULL UNIQUE,
            domain VARCHAR(255) NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE domains (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            hostname VARCHAR(255) NOT NULL UNIQUE,
            site_slug VARCHAR(191) NOT NULL,
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE ingest_agents (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL UNIQUE,
            token_hash VARCHAR(64) NOT NULL UNIQUE,
            sites TEXT NOT NULL,
            desks TEXT NOT NULL DEFAULT '',
            enabled INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMP NOT NULL,
            last_used_at TIMESTAMP
        );

CREATE TABLE media_clients (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL UNIQUE,
            token_hash VARCHAR(64) NOT NULL UNIQUE,
            scopes VARCHAR(255) NOT NULL,
            enabled INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMP NOT NULL,
            last_used_at TIMESTAMP
        );

CREATE TABLE story_sources (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            post_id INTEGER NOT NULL,
            url VARCHAR(600) NOT NULL,
            title VARCHAR(255) NOT NULL DEFAULT '',
            retrieved_at TIMESTAMP,
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE social_shares (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            post_id INTEGER NOT NULL,
            platform VARCHAR(20) NOT NULL,
            post_title VARCHAR(255) NOT NULL DEFAULT '',
            post_content TEXT,
            image_url VARCHAR(500) NOT NULL DEFAULT '',
            is_posted INTEGER NOT NULL DEFAULT 0,
            posted_at TIMESTAMP,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT uq_social_share UNIQUE (post_id, platform)
        );

CREATE TABLE users (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL,
            email VARCHAR(191) NOT NULL UNIQUE,
            pass_hash VARCHAR(255) NOT NULL,
            role VARCHAR(20) NOT NULL DEFAULT 'author',
            slug VARCHAR(191) NOT NULL DEFAULT '',
            title VARCHAR(120) NOT NULL DEFAULT '',
            bio TEXT,
            photo VARCHAR(255) NOT NULL DEFAULT '',
            totp_secret VARCHAR(64) NOT NULL DEFAULT '',
            totp_enabled INTEGER NOT NULL DEFAULT 0,
            session_epoch INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE categories (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL,
            slug VARCHAR(191) NOT NULL UNIQUE,
            color VARCHAR(20) NOT NULL DEFAULT '#17301C',
            color_is_fill INTEGER NOT NULL DEFAULT 0,
            description TEXT,
            sort INTEGER NOT NULL DEFAULT 0
        );

CREATE TABLE posts (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            slug VARCHAR(191) NOT NULL UNIQUE,
            category_id INTEGER,
            author_id INTEGER,
            byline VARCHAR(120) NOT NULL DEFAULT '',
            dateline VARCHAR(120) NOT NULL DEFAULT '',
            lede TEXT,
            body TEXT,
            image VARCHAR(255) NOT NULL DEFAULT '',
            image_caption VARCHAR(255) NOT NULL DEFAULT '',
            image_credit VARCHAR(120) NOT NULL DEFAULT '',
            meta_description VARCHAR(255) NOT NULL DEFAULT '',
            source_url VARCHAR(500) NOT NULL DEFAULT '',
            source_name VARCHAR(160) NOT NULL DEFAULT '',
            post_type VARCHAR(20) NOT NULL DEFAULT 'story',
            region VARCHAR(40) NOT NULL DEFAULT '',
            origin VARCHAR(20) NOT NULL DEFAULT '',
            canonical_site_id INTEGER,
            status VARCHAR(20) NOT NULL DEFAULT 'draft',
            review_note TEXT,
            is_featured INTEGER NOT NULL DEFAULT 0,
            placement VARCHAR(20) NOT NULL DEFAULT '',
            views INTEGER NOT NULL DEFAULT 0,
            correction TEXT,
            corrected_at TIMESTAMP,
            published_at TIMESTAMP,
            filed_by VARCHAR(120) NOT NULL DEFAULT '',
            content_hash VARCHAR(64) NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        );

CREATE TABLE post_sites (
            post_id INTEGER NOT NULL,
            site_id INTEGER NOT NULL,
            PRIMARY KEY (post_id, site_id)
        );

CREATE TABLE tags (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL,
            slug VARCHAR(191) NOT NULL UNIQUE
        );

CREATE TABLE post_tags (
            post_id INTEGER NOT NULL,
            tag_id INTEGER NOT NULL,
            PRIMARY KEY (post_id, tag_id)
        );

CREATE TABLE sources (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(160) NOT NULL,
            url VARCHAR(500) NOT NULL,
            region VARCHAR(40) NOT NULL,
            enabled INTEGER NOT NULL DEFAULT 1,
            last_fetched_at TIMESTAMP,
            last_status VARCHAR(255) NOT NULL DEFAULT ''
        );

CREATE TABLE news_items (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            source_id INTEGER NOT NULL,
            region VARCHAR(40) NOT NULL,
            title VARCHAR(500) NOT NULL,
            url VARCHAR(600) NOT NULL,
            url_hash CHAR(40) NOT NULL UNIQUE,
            summary TEXT,
            published_at TIMESTAMP,
            fetched_at TIMESTAMP NOT NULL,
            used INTEGER NOT NULL DEFAULT 0
        );

CREATE TABLE subscribers (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            site_id INTEGER NOT NULL DEFAULT 1,
            email VARCHAR(191) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'active',
            token VARCHAR(64) NOT NULL DEFAULT '',
            confirmed_at TIMESTAMP,
            consent_note VARCHAR(255) NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL,
            CONSTRAINT uq_sub UNIQUE (site_id, email)
        );

CREATE TABLE newsletters (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            site_id INTEGER NOT NULL,
            edition_date VARCHAR(10) NOT NULL,
            subject VARCHAR(255) NOT NULL,
            html TEXT,
            status VARCHAR(20) NOT NULL DEFAULT 'sent',
            recipients INTEGER NOT NULL DEFAULT 0,
            sent_at TIMESTAMP,
            created_at TIMESTAMP NOT NULL,
            CONSTRAINT uq_edition UNIQUE (site_id, edition_date)
        );

CREATE TABLE settings (
            site_id INTEGER NOT NULL,
            skey VARCHAR(100) NOT NULL,
            svalue TEXT,
            PRIMARY KEY (site_id, skey)
        );

CREATE TABLE ads (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            site_id INTEGER NOT NULL,
            name VARCHAR(160) NOT NULL,
            placement VARCHAR(20) NOT NULL DEFAULT 'rail',
            kind VARCHAR(20) NOT NULL DEFAULT 'house',
            image VARCHAR(255) NOT NULL DEFAULT '',
            link_url VARCHAR(500) NOT NULL DEFAULT '',
            html TEXT,
            kicker VARCHAR(80) NOT NULL DEFAULT '',
            heading VARCHAR(160) NOT NULL DEFAULT '',
            body_text VARCHAR(255) NOT NULL DEFAULT '',
            button_label VARCHAR(60) NOT NULL DEFAULT '',
            start_at TIMESTAMP,
            end_at TIMESTAMP,
            enabled INTEGER NOT NULL DEFAULT 1,
            impressions INTEGER NOT NULL DEFAULT 0,
            clicks INTEGER NOT NULL DEFAULT 0,
            campaign_id INTEGER,
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE campaigns (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(160) NOT NULL,
            advertiser VARCHAR(160) NOT NULL DEFAULT '',
            notes TEXT,
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE inquiries (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            site_id INTEGER NOT NULL,
            name VARCHAR(120) NOT NULL DEFAULT '',
            email VARCHAR(191) NOT NULL DEFAULT '',
            organization VARCHAR(160) NOT NULL DEFAULT '',
            message TEXT,
            status VARCHAR(20) NOT NULL DEFAULT 'new',
            ip VARCHAR(64) NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE roadmap_items (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            kind VARCHAR(20) NOT NULL DEFAULT 'note',
            title VARCHAR(255) NOT NULL,
            body TEXT,
            status VARCHAR(20) NOT NULL DEFAULT '',
            sort INTEGER NOT NULL DEFAULT 0,
            updated_by VARCHAR(120) NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        );

CREATE TABLE monitor_feeds (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(160) NOT NULL,
            url VARCHAR(600) NOT NULL,
            level VARCHAR(20) NOT NULL DEFAULT 'agency',
            region VARCHAR(40) NOT NULL DEFAULT '',
            doc_type VARCHAR(30) NOT NULL DEFAULT 'release',
            enabled INTEGER NOT NULL DEFAULT 1,
            last_fetched_at TIMESTAMP,
            last_status VARCHAR(255) NOT NULL DEFAULT ''
        );

CREATE TABLE monitor_items (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            feed_id INTEGER,
            source_name VARCHAR(160) NOT NULL DEFAULT '',
            level VARCHAR(20) NOT NULL DEFAULT 'agency',
            region VARCHAR(40) NOT NULL DEFAULT '',
            doc_type VARCHAR(30) NOT NULL DEFAULT 'other',
            title VARCHAR(255) NOT NULL,
            url VARCHAR(600) NOT NULL,
            url_hash VARCHAR(40) NOT NULL UNIQUE,
            summary TEXT,
            body_excerpt TEXT,
            published_at TIMESTAMP,
            fetched_at TIMESTAMP NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'new',
            flagged_by VARCHAR(120) NOT NULL DEFAULT '',
            claimed_by VARCHAR(120) NOT NULL DEFAULT ''
        );

CREATE TABLE story_ideas (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            monitor_item_id INTEGER,
            site_id INTEGER,
            title VARCHAR(255) NOT NULL,
            angle TEXT,
            rationale TEXT,
            region VARCHAR(40) NOT NULL DEFAULT '',
            origin VARCHAR(20) NOT NULL DEFAULT 'newsroom',
            status VARCHAR(20) NOT NULL DEFAULT 'open',
            claimed_by VARCHAR(120) NOT NULL DEFAULT '',
            created_by VARCHAR(120) NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE media_requests (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            public_ref VARCHAR(64) NOT NULL UNIQUE,
            client_id INTEGER NOT NULL,
            idempotency_key VARCHAR(191) NOT NULL,
            pantheon_request_id VARCHAR(80) NOT NULL,
            pantheon_brief_id VARCHAR(80) NOT NULL,
            schema_version VARCHAR(20) NOT NULL,
            request_kind VARCHAR(30) NOT NULL,
            title VARCHAR(255) NOT NULL,
            advertiser VARCHAR(160),
            sponsor VARCHAR(160),
            disclosure TEXT,
            landing_url VARCHAR(600),
            desired_start VARCHAR(10),
            desired_end VARCHAR(10),
            max_budget DECIMAL(14,2),
            currency VARCHAR(3) NOT NULL DEFAULT 'CAD',
            target_json TEXT,
            content_json TEXT,
            notes TEXT,
            state VARCHAR(30) NOT NULL DEFAULT 'received',
            review_note TEXT,
            quote_ref VARCHAR(80),
            quote_amount DECIMAL(14,2),
            quote_currency VARCHAR(3),
            quote_valid_until TIMESTAMP,
            quote_terms TEXT,
            reviewed_by VARCHAR(120) NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT uq_media_request_idempotency UNIQUE (client_id, idempotency_key),
            CONSTRAINT uq_media_request_pantheon UNIQUE (client_id, pantheon_request_id)
        );

CREATE TABLE media_request_sites (
            request_id INTEGER NOT NULL,
            site_id INTEGER NOT NULL,
            product_ref VARCHAR(191) NOT NULL,
            budget_cap DECIMAL(14,2),
            creative_json TEXT,
            state VARCHAR(30) NOT NULL DEFAULT 'requested',
            PRIMARY KEY (request_id, site_id)
        );

CREATE TABLE media_request_outputs (
            request_id INTEGER NOT NULL,
            site_id INTEGER NOT NULL DEFAULT 0,
            output_kind VARCHAR(30) NOT NULL,
            output_id INTEGER NOT NULL,
            created_at TIMESTAMP NOT NULL,
            CONSTRAINT uq_media_request_output UNIQUE (request_id, site_id, output_kind, output_id)
        );

CREATE TABLE media_request_events (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            request_id INTEGER NOT NULL,
            event_type VARCHAR(40) NOT NULL,
            actor VARCHAR(120) NOT NULL,
            payload TEXT,
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE media_orders (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            order_ref VARCHAR(64) NOT NULL UNIQUE,
            request_id INTEGER NOT NULL,
            client_id INTEGER NOT NULL,
            idempotency_key VARCHAR(191) NOT NULL,
            pantheon_order_id VARCHAR(80) NOT NULL,
            quote_ref VARCHAR(80) NOT NULL,
            approval_ref VARCHAR(160) NOT NULL,
            amount_cap DECIMAL(14,2) NOT NULL,
            currency VARCHAR(3) NOT NULL,
            desired_start VARCHAR(10),
            desired_end VARCHAR(10),
            state VARCHAR(30) NOT NULL DEFAULT 'booked',
            state_note TEXT,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT uq_media_order_idempotency UNIQUE (client_id, idempotency_key),
            CONSTRAINT uq_media_order_pantheon UNIQUE (client_id, pantheon_order_id)
        );

CREATE TABLE site_metrics_daily (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            site_id INTEGER NOT NULL,
            day DATE NOT NULL,
            sessions INTEGER NOT NULL DEFAULT 0,
            users INTEGER NOT NULL DEFAULT 0,
            pageviews INTEGER NOT NULL DEFAULT 0,
            engaged_sessions INTEGER NOT NULL DEFAULT 0,
            engagement_secs INTEGER NOT NULL DEFAULT 0,
            channels_json TEXT,
            top_pages_json TEXT
        );

CREATE TABLE gsc_daily (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            site_id INTEGER NOT NULL,
            day DATE NOT NULL,
            dim VARCHAR(10) NOT NULL,
            dkey VARCHAR(255) NOT NULL,
            clicks INTEGER NOT NULL DEFAULT 0,
            impressions INTEGER NOT NULL DEFAULT 0,
            position REAL NOT NULL DEFAULT 0
        );

CREATE TABLE entities (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name VARCHAR(160) NOT NULL,
            slug VARCHAR(191) NOT NULL UNIQUE,
            kind VARCHAR(40) NOT NULL DEFAULT 'politician',
            url VARCHAR(600) NOT NULL DEFAULT '',
            aliases TEXT,
            enabled INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE agent_tasks (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            kind VARCHAR(40) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'queued',
            post_id INTEGER,
            site_id INTEGER,
            payload TEXT,
            result TEXT,
            log TEXT,
            created_by VARCHAR(120) NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL,
            started_at TIMESTAMP,
            finished_at TIMESTAMP,
            reviewed_by VARCHAR(120) NOT NULL DEFAULT '',
            reviewed_at TIMESTAMP
        );

CREATE TABLE login_attempts (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            email VARCHAR(191) NOT NULL DEFAULT '',
            ip VARCHAR(64) NOT NULL DEFAULT '',
            succeeded INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE audit_log (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            site_id INTEGER NOT NULL DEFAULT 0,
            user_id INTEGER NOT NULL DEFAULT 0,
            user_name VARCHAR(120) NOT NULL DEFAULT '',
            action VARCHAR(60) NOT NULL,
            target VARCHAR(160) NOT NULL DEFAULT '',
            detail TEXT,
            ip VARCHAR(64) NOT NULL DEFAULT '',
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE post_revisions (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            post_id INTEGER NOT NULL,
            title VARCHAR(255) NOT NULL DEFAULT '',
            lede TEXT,
            body TEXT,
            meta_description VARCHAR(255) NOT NULL DEFAULT '',
            correction TEXT,
            image VARCHAR(255) NOT NULL DEFAULT '',
            image_caption VARCHAR(255) NOT NULL DEFAULT '',
            saved_by VARCHAR(120) NOT NULL DEFAULT '',
            reason VARCHAR(40) NOT NULL DEFAULT 'edit',
            created_at TIMESTAMP NOT NULL
        );

CREATE TABLE ops_runs (
            id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            job VARCHAR(40) NOT NULL,
            site_id INTEGER NOT NULL DEFAULT 0,
            ok INTEGER NOT NULL DEFAULT 1,
            note VARCHAR(500) NOT NULL DEFAULT '',
            started_at TIMESTAMP NOT NULL,
            finished_at TIMESTAMP
        );

CREATE INDEX idx_posts_status ON posts (status, published_at);

CREATE INDEX idx_social_shares_post ON social_shares (post_id);

CREATE INDEX idx_agent_tasks ON agent_tasks (status, created_at);

CREATE INDEX idx_agent_tasks_post ON agent_tasks (post_id, kind);

CREATE UNIQUE INDEX uq_metrics_site_day ON site_metrics_daily (site_id, day);

CREATE UNIQUE INDEX uq_gsc_row ON gsc_daily (site_id, day, dim, dkey);

CREATE INDEX idx_gsc_site_dim ON gsc_daily (site_id, dim, day);

CREATE INDEX idx_posts_category ON posts (category_id);

CREATE INDEX idx_posts_author ON posts (author_id);

CREATE INDEX idx_posts_region ON posts (region);

CREATE INDEX idx_news_region ON news_items (region, fetched_at);

CREATE INDEX idx_monitor_items ON monitor_items (level, region, fetched_at);

CREATE INDEX idx_monitor_status ON monitor_items (status, fetched_at);

CREATE INDEX idx_ideas_status ON story_ideas (status, created_at);

CREATE INDEX idx_post_sites_site ON post_sites (site_id);

CREATE INDEX idx_domains_site ON domains (site_slug);

CREATE INDEX idx_story_sources_post ON story_sources (post_id);

CREATE INDEX idx_posts_content_hash ON posts (content_hash);

CREATE INDEX idx_ads_site_placement ON ads (site_id, placement);

CREATE INDEX idx_ads_campaign ON ads (campaign_id);

CREATE INDEX idx_inquiries_site ON inquiries (site_id, created_at);

CREATE INDEX idx_login_attempts_email ON login_attempts (email, created_at);

CREATE INDEX idx_login_attempts_ip ON login_attempts (ip, created_at);

CREATE INDEX idx_audit_created ON audit_log (created_at);

CREATE INDEX idx_revisions_post ON post_revisions (post_id, id);

CREATE INDEX idx_ops_runs_job ON ops_runs (job, id);

CREATE INDEX idx_media_requests_state ON media_requests (state, request_kind, updated_at);

CREATE INDEX idx_media_requests_client ON media_requests (client_id, created_at);

CREATE INDEX idx_media_request_sites_site ON media_request_sites (site_id, state);

CREATE INDEX idx_media_request_outputs_request ON media_request_outputs (request_id);

CREATE INDEX idx_media_request_events_request ON media_request_events (request_id, id);

CREATE INDEX idx_media_orders_request ON media_orders (request_id, state);

CREATE TABLE schema_migrations (
        version INTEGER NOT NULL PRIMARY KEY,
        name VARCHAR(190) NOT NULL DEFAULT '',
        checksum VARCHAR(64) NOT NULL DEFAULT '',
        status VARCHAR(16) NOT NULL,
        started_at TIMESTAMP NOT NULL,
        finished_at TIMESTAMP
    );

INSERT INTO settings (site_id, skey, svalue) VALUES (0, 'schema_version', '19');
INSERT INTO schema_migrations (version, name, checksum, status, started_at, finished_at)
VALUES (19, 'bootstrapped from supabase/schema.sql', '', 'installed', now(), now());
