<?php
/**
 * supabase/schema.sql is GENERATED from the authoritative schema
 * definition (pp_schema_ddl in app/db.php) — never hand-edited, so the
 * standalone SQL bootstrap can no longer drift from what the application
 * installs (the audited copy described version 17 while the code was 19).
 *
 *   php tools/schema-sql.php --check    verify the committed file matches (CI)
 *   php tools/schema-sql.php --write    regenerate it
 *
 * A database bootstrapped from this file is IDENTICAL to one installed by
 * `php tools/migrate.php --apply` on Postgres: same objects, same journal,
 * same version stamp — the parity test proves it against live catalogs.
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit("CLI only.\n");
}

define('PP_ROOT', dirname(__DIR__));
require PP_ROOT . '/app/helpers.php';
require PP_ROOT . '/app/db.php';

// pp_pg_schema() reads config; the generated file targets the DEFAULT
// namespace and says so — a custom schema wraps it in its own search_path.
$GLOBALS['pp_config'] = ['db' => ['pgsql' => ['schema' => 'prairiedispatch']]];
// Read the version constant from bootstrap without booting it.
preg_match("/define\('PP_SCHEMA_VERSION', (\d+)\);/", (string) file_get_contents(PP_ROOT . '/app/bootstrap.php'), $m);
$version = (int) ($m[1] ?? 0);
if ($version < 19) {
    fwrite(STDERR, "could not read PP_SCHEMA_VERSION from app/bootstrap.php\n");
    exit(2);
}

$mode = $argv[1] ?? '';
if (!in_array($mode, ['--check', '--write'], true)) {
    fwrite(STDERR, "Usage: php tools/schema-sql.php --check | --write\n");
    exit(2);
}

$lines = [];
$lines[] = '-- ============================================================================';
$lines[] = '-- The Prairie Dispatch network — shared content database schema (Postgres).';
$lines[] = '--';
$lines[] = '-- GENERATED by tools/schema-sql.php from app/db.php (pp_schema_ddl).';
$lines[] = '-- Do not hand-edit; regenerate with:  php tools/schema-sql.php --write';
$lines[] = '--';
$lines[] = '-- Standalone bootstrap for schema version ' . $version . '. Equivalent to running';
$lines[] = '--   php tools/migrate.php --apply';
$lines[] = '-- against an empty target. The application does NOT install anything on';
$lines[] = '-- first connection — an unprepared database answers 503 until the';
$lines[] = '-- migration runner (or this file) has prepared it.';
$lines[] = '--';
$lines[] = '-- Runs in the app\'s own namespace; adjust the schema name to taste.';
$lines[] = '-- ============================================================================';
$lines[] = '';
$lines[] = 'CREATE SCHEMA IF NOT EXISTS prairiedispatch;';
$lines[] = 'SET search_path TO prairiedispatch;';
$lines[] = '';
foreach (pp_schema_ddl('pgsql') as $stmt) {
    $lines[] = rtrim($stmt) . ';';
    $lines[] = '';
}
$lines[] = rtrim(pp_journal_ddl('pgsql')) . ';';
$lines[] = '';
$lines[] = "INSERT INTO settings (site_id, skey, svalue) VALUES (0, 'schema_version', '" . $version . "');";
$lines[] = "INSERT INTO schema_migrations (version, name, checksum, status, started_at, finished_at)";
$lines[] = "VALUES (" . $version . ", 'bootstrapped from supabase/schema.sql', '', 'installed', now(), now());";
$lines[] = '';
$generated = implode("\n", $lines);

$file = PP_ROOT . '/supabase/schema.sql';
if ($mode === '--write') {
    file_put_contents($file, $generated);
    echo "written: supabase/schema.sql (schema version $version, " . substr_count($generated, ';') . " statements)\n";
    exit(0);
}
$committed = (string) @file_get_contents($file);
if ($committed === $generated) {
    echo "supabase/schema.sql matches the authoritative definition (version $version).\n";
    exit(0);
}
fwrite(STDERR, "supabase/schema.sql DIVERGES from app/db.php — regenerate it:\n"
    . "  php tools/schema-sql.php --write\n");
exit(1);
