#!/usr/bin/env bash
#
# Prove the path protections on the REAL servers — nginx + PHP-FPM and
# Apache + FPM — not just on the dev router (the Phase 1 gap). Uses a
# disposable release fixture (git archive of HEAD with its own real
# config.php and a prepared sqlite database; PP_CONFIG plays no part,
# because FPM never honors it) and planted sentinels (.git/config, a PHP
# file under uploads/) that must never be served or executed.
#
#   bash tools/test-server-enforcement.sh          both servers
#   bash tools/test-server-enforcement.sh nginx    one of them
#   bash tools/test-server-enforcement.sh apache
#
# nginx runs three blocks: one generated by tools/vps/make-vhost.sh (a
# NEW site), one LEGACY-style block carrying only the old app|data rules
# plus the injected shared deny snippet (an EXISTING site after the
# upgrade roll patches it), and one whose release points at a missing
# database (the controlled 503 surface). Apache exercises the COMMITTED
# .htaccess through AllowOverride All.
#
set -uo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)
ONLY="${1:-both}"
FAILS=0
W=$(mktemp -d)
PIDS=()
cleanup() {
  for p in "${PIDS[@]}"; do kill "$p" 2>/dev/null; done
  sleep 0.5
  rm -rf "$W"
}
trap cleanup EXIT

say() { echo; echo "== $*"; }
ok() { if eval "$2"; then echo "ok   $1"; else echo "FAIL $1"; FAILS=1; fi; }

say "Build the disposable release fixture"
mkdir -p "$W/rel"
git archive HEAD | tar -x -C "$W/rel"
cat > "$W/rel/config.php" <<CFG
<?php
return ['db' => ['driver' => 'sqlite', 'sqlite_path' => '$W/rel/data/app.sqlite'],
        'site_slug' => 'prairiedispatch', 'hub_slug' => 'civismedia',
        'site_url' => '', 'timezone' => 'America/Toronto', 'debug' => false];
CFG
( cd "$W/rel" && php tools/migrate.php --apply >/dev/null && php tools/seed-core.php >/dev/null ) || { echo "FATAL: fixture prepare failed"; exit 1; }
# Sentinels that must never leave the box.
mkdir -p "$W/rel/.git" "$W/rel/uploads/2026"
echo "SENTINEL-GIT-CONFIG" > "$W/rel/.git/config"
printf '<?php echo "SENTINEL-EXECUTED";\n' > "$W/rel/uploads/2026/evil.php"
echo "SENTINEL-UPLOAD-OK" > "$W/rel/uploads/2026/fine.txt"
# A broken twin for the controlled 503 surface.
cp -r "$W/rel" "$W/broken"
sed -i "s|$W/rel/data/app.sqlite|$W/broken/data/missing.sqlite|" "$W/broken/config.php"
rm -f "$W/broken/data/missing.sqlite"
chmod -R a+rX "$W"
# sqlite WAL needs writable journals next to the file; the FPM pool runs
# as www-data on this root-owned fixture.
chmod -R a+rwX "$W/rel/data" "$W/broken/data"

say "Start PHP-FPM on a private socket"
cat > "$W/fpm.conf" <<FPM
[global]
pid = $W/fpm.pid
error_log = $W/fpm.log
daemonize = no
[pp]
listen = $W/php.sock
listen.mode = 0666
user = www-data
group = www-data
pm = static
pm.max_children = 4
FPM
php-fpm8.4 -y "$W/fpm.conf" -R >/dev/null 2>&1 &
PIDS+=($!)
sleep 1
[ -S "$W/php.sock" ] || { echo "FATAL: FPM socket did not appear ($(tail -3 "$W/fpm.log" 2>/dev/null))"; exit 1; }
php-fpm8.4 -m 2>/dev/null | grep -qi '^dom$' || { echo "FATAL: FPM build lacks ext-dom"; exit 1; }
echo "   FPM up (ext-dom present)"

req() { # port path [host] -> CODE|HEADERS_FILE|BODY_FILE
  local port="$1" path="$2" host="${3:-pp.test}"
  curl -s -m 10 -H "Host: $host" -o "$W/body" -D "$W/head" -w '%{http_code}' "http://127.0.0.1:$port$path"
}
run_matrix() { # server-label port broken-port
  local L="$1" P="$2" BP="$3"
  local c
  for path in "/app/helpers.php" "/app/config.site.php" "/data/app.sqlite" \
              "/tools/reset-password.php" "/tools/migrate.php" "/tools/backup.sh" \
              "/tests/run.php" "/vendor/ezyang/htmlpurifier/library/HTMLPurifier.php" \
              "/docs/MIGRATION-COMPAT.md" "/.git/config" "/.htaccess" \
              "/composer.json" "/composer.lock" "/router.php" "/CLAUDE.md"; do
    c=$(req "$P" "$path")
    ok "$L denies $path ($c)" "[ $c -ge 400 ] && ! grep -q SENTINEL-GIT-CONFIG '$W/body' && ! grep -q '<?php' '$W/body'"
  done
  c=$(req "$P" "/uploads/2026/evil.php")
  ok "$L never executes PHP under uploads ($c)" "[ $c -ge 400 ] && ! grep -q SENTINEL-EXECUTED '$W/body'"
  c=$(req "$P" "/uploads/2026/fine.txt")
  ok "$L serves legitimate uploads ($c)" "[ $c = 200 ] && grep -q SENTINEL-UPLOAD-OK '$W/body'"
  c=$(req "$P" "/")
  ok "$L serves the front page ($c)" "[ $c = 200 ] && grep -q 'Prairie Dispatch' '$W/body'"
  ok "$L front page went through the sanitizer stack (FPM ext-dom)" "grep -q '</html>' '$W/body'"
  c=$(req "$P" "/assets/css/prairie.css")
  ok "$L serves stylesheets ($c)" "[ $c = 200 ]"
  c=$(req "$P" "/feed/")
  ok "$L routes the feed ($c)" "[ $c = 200 ]"
  c=$(req "$P" "/cron/fetch-news.php")
  ok "$L web-cron without the secret answers 403 ($c)" "[ $c = 403 ]"
  c=$(req "$P" "/.well-known/acme-challenge/probe-token")
  ok "$L keeps the ACME path routable ($c = missing token, not policy)" "[ $c = 404 ]"
  # The controlled schema-unavailable surface.
  c=$(req "$BP" "/")
  ok "$L broken-schema front answers 503 ($c)" "[ $c = 503 ]"
  ok "$L 503 is non-cacheable" "grep -qi 'Cache-Control: no-store' '$W/head'"
  ok "$L 503 leaks no internals" "! grep -qE 'PDO|SQLSTATE|sqlite' '$W/body'"
  c=$(req "$BP" "/assets/css/prairie.css")
  ok "$L broken-schema still serves static assets ($c)" "[ $c = 200 ]"
}

if [ "$ONLY" = "both" ] || [ "$ONLY" = "nginx" ]; then
  say "nginx: generated block + patched legacy block + broken-schema block"
  mkdir -p "$W/snippets"
  cp tools/vps/pp-deny.conf "$W/snippets/prairiepost-deny.conf"
  cp /etc/nginx/fastcgi_params "$W/"   # relative includes resolve against the conf dir here
  bash tools/vps/make-vhost.sh "$W/rel" "$W/php.sock" pp.test www.pp.test > "$W/vh-new.conf"
  sed -i -e 's/listen 80;/listen 127.0.0.1:8890;/' -e '/listen \[::\]:80;/d' "$W/vh-new.conf"
  cat > "$W/nginx.conf" <<NG
pid $W/nginx.pid;
error_log $W/nginx-err.log;
events {}
http {
  include /etc/nginx/mime.types;
  access_log off;
  server_names_hash_bucket_size 64;
  include $W/vh-new.conf;
  # A LEGACY block: pre-Phase-1 rules only, PLUS the snippet the upgrade
  # roll injects into existing sites — this is what live papers become.
  # Crucially it carries its OWN ACME and dotfile locations, as every
  # production block does: the 4163fe0 roll was rejected by nginx over
  # duplicate locations when the snippet ALSO carried them, so this
  # nginx -t is the regression test that the snippet stays collision-free.
  server {
    listen 127.0.0.1:8891;
    server_name legacy.test;
    root $W/rel;
    index index.php;
    location ^~ /.well-known/acme-challenge/ { try_files \$uri =404; }
    location ~ /\. { deny all; }
    include $W/snippets/prairiepost-deny.conf;
    location ~ ^/(app|data)/ { deny all; }
    location / { try_files \$uri /router.php\$is_args\$args; }
    location = /router.php {
      internal;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
      fastcgi_pass unix:$W/php.sock;
    }
    location ~ \.php\$ {
      try_files \$uri =404;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
      fastcgi_pass unix:$W/php.sock;
    }
  }
  server {
    listen 127.0.0.1:8892;
    server_name broken.test;
    root $W/broken;
    index index.php;
    location ^~ /.well-known/acme-challenge/ { try_files \$uri =404; }
    location ~ /\. { deny all; }
    include $W/snippets/prairiepost-deny.conf;
    location / { try_files \$uri /router.php\$is_args\$args; }
    location = /router.php {
      internal;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
      fastcgi_pass unix:$W/php.sock;
    }
    location ~ \.php\$ {
      try_files \$uri =404;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
      fastcgi_pass unix:$W/php.sock;
    }
  }
}
NG
  nginx -p /etc/nginx -c "$W/nginx.conf" -g "daemon off;" >/dev/null 2>&1 &
  PIDS+=($!)
  sleep 1
  run_matrix "nginx(new-template)" 8890 8892
  run_matrix "nginx(patched-legacy)" 8891 8892
fi

if [ "$ONLY" = "both" ] || [ "$ONLY" = "apache" ]; then
  say "Apache: the committed .htaccess through AllowOverride All"
  M=/usr/lib/apache2/modules
  cat > "$W/apache.conf" <<AP
ServerRoot "$W"
PidFile $W/apache.pid
ErrorLog $W/apache-err.log
Mutex file:$W default
LoadModule mpm_event_module $M/mod_mpm_event.so
LoadModule authz_core_module $M/mod_authz_core.so
LoadModule authz_host_module $M/mod_authz_host.so
LoadModule dir_module $M/mod_dir.so
LoadModule mime_module $M/mod_mime.so
LoadModule rewrite_module $M/mod_rewrite.so
LoadModule proxy_module $M/mod_proxy.so
LoadModule proxy_fcgi_module $M/mod_proxy_fcgi.so
LoadModule env_module $M/mod_env.so
TypesConfig /etc/mime.types
User www-data
Group www-data
Listen 127.0.0.1:8893
ServerName pp.test
DocumentRoot "$W/rel"
DirectoryIndex index.php
<Directory "$W/rel">
  Options FollowSymLinks
  AllowOverride All
  Require all granted
</Directory>
<FilesMatch "\.php\$">
  SetHandler "proxy:unix:$W/php.sock|fcgi://localhost"
</FilesMatch>
AP
  apache2 -f "$W/apache.conf" -D FOREGROUND >/dev/null 2>&1 &
  PIDS+=($!)
  sleep 1.5
  # Apache has no broken-schema block of its own; reuse nginx's if present,
  # else run a second Apache on the broken root.
  BROKENPORT=8892
  if [ "$ONLY" = "apache" ]; then
    sed -e "s|8893|8894|" -e "s|$W/rel|$W/broken|g" -e "s|apache.pid|apache2.pid|" "$W/apache.conf" > "$W/apache-broken.conf"
    apache2 -f "$W/apache-broken.conf" -D FOREGROUND >/dev/null 2>&1 &
    PIDS+=($!)
    sleep 1
    BROKENPORT=8894
  elif true; then
    sed -e "s|8893|8894|" -e "s|$W/rel|$W/broken|g" -e "s|apache.pid|apache2.pid|" "$W/apache.conf" > "$W/apache-broken.conf"
    apache2 -f "$W/apache-broken.conf" -D FOREGROUND >/dev/null 2>&1 &
    PIDS+=($!)
    sleep 1
    BROKENPORT=8894
  fi
  run_matrix "apache(.htaccess)" 8893 "$BROKENPORT"
fi

echo
if [ "$FAILS" = "1" ]; then
  echo "SERVER ENFORCEMENT BROKEN — the rules that pass on the dev router do not hold on a real server."
  exit 1
fi
echo "All real-server enforcement checks pass."
