#!/usr/bin/env bash
#
# Civis Media — Phase 1 deploy for the network's VPS.
# Follows the box's own convention: a fresh /var/www/prairiepost-<sha>
# release directory for the hub, its own nginx vhost, its own cert.
# Touches NOTHING the papers serve from. The only shared change is the
# database's additive migrations, which run on the hub's first boot.
#
# Secrets never appear here: the database credentials are copied on the
# box, from the Prairie Dispatch's existing config.php.
#
# Run as root:  curl -fsSL <raw url> | bash
#
set -uo pipefail

REPO="FTFNAnalytics/prairiepost"
BRANCH="claude/master-dashboard-control-room-nr3mp4"
DOMAIN="civismedia.ca"
FPM_SOCK="/run/php/php8.3-fpm.sock"

say()  { echo; echo "== $*"; }
fail() { echo "FATAL: $*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || fail "run as root (the browser terminal is root already)"
command -v nginx >/dev/null || fail "nginx not found"
command -v php   >/dev/null || fail "php not found"
[ -S "$FPM_SOCK" ] || fail "php-fpm socket $FPM_SOCK not found"

say "Resolve the branch head"
SHA=$(curl -fsSL "https://api.github.com/repos/$REPO/branches/${BRANCH//\//%2F}" \
      | php -r '$d=json_decode(stream_get_contents(STDIN),true); echo substr($d["commit"]["sha"]??"",0,12);')
[ -n "$SHA" ] || SHA="civis-$(date +%Y%m%d%H%M)"
REL="/var/www/prairiepost-$SHA"
echo "release directory: $REL"

say "Fetch the release"
if [ -d "$REL" ]; then
  echo "already present — reusing (re-run friendly)"
else
  TMP=$(mktemp -d)
  curl -fsSL "https://codeload.github.com/$REPO/tar.gz/refs/heads/$BRANCH" -o "$TMP/rel.tgz" \
    || fail "couldn't download the branch tarball"
  tar -xzf "$TMP/rel.tgz" -C "$TMP" || fail "tarball didn't extract"
  INNER=$(find "$TMP" -maxdepth 1 -mindepth 1 -type d | head -1)
  [ -f "$INNER/app/bootstrap.php" ] || fail "extracted tree doesn't look like the app"
  mv "$INNER" "$REL"
  rm -rf "$TMP"
fi

say "Build the hub's config.php from the Dispatch's (credentials stay on this box)"
# A release's config comes in two shapes: a single config.php, or a
# generated wrapper whose real configuration is app/config.site.php
# (what upgrade-papers.sh writes). Match and use whichever carries it.
SRCCFG=""
for d in /var/www/prairiepost-*; do
  for f in "$d/app/config.site.php" "$d/config.php"; do
    [ -f "$f" ] && grep -q "'site_slug' => 'prairiedispatch'" "$f" && SRCCFG="$f" && break 2
  done
done
[ -n "$SRCCFG" ] || fail "no existing config with site_slug prairiedispatch found to copy the db block from"
echo "config source: $SRCCFG"

# Hub-only secrets (the research desk's API key) survive re-deploys: carry
# them from the config the civismedia vhost serves right now. Only a static
# file this script itself generated is ever evaluated — the grep guard proves
# the literal slug is there before anything is required.
PREV=""
HUBVH=$(readlink -f /etc/nginx/sites-enabled/civismedia 2>/dev/null || true)
if [ -n "$HUBVH" ] && [ -f "$HUBVH" ]; then
  PREVROOT=$(grep -Eo 'root[[:space:]]+/var/www/prairiepost-[A-Za-z0-9._-]+' "$HUBVH" | head -1 | awk '{print $2}')
  for f in "$PREVROOT/app/config.site.php" "$PREVROOT/config.php"; do
    if [ -n "$PREVROOT" ] && [ -f "$f" ] \
       && grep -q "'site_slug' => 'civismedia'" "$f"; then
      PREV="$f"
      echo "carrying hub secrets forward from: $PREV"
      break
    fi
  done
fi
php -r '
$c = require $argv[1];
$c["site_slug"] = "civismedia";
$c["hub_slug"]  = "civismedia";   // the control room lives on this site
$c["site_url"]  = "https://civismedia.ca";
if ($argv[3] !== "" && is_file($argv[3])) {
    $prev = require $argv[3];     // static hub config generated by this script
    foreach (["anthropic_api_key", "anthropic_base_url", "google_sa_json"] as $k) {
        if (is_array($prev) && !empty($prev[$k])) {
            $c[$k] = $prev[$k];
        }
    }
}
file_put_contents($argv[2], "<?php\n// Civis Media — the hub. Generated by deploy-civis.sh from the Dispatch config.\nreturn " . var_export($c, true) . ";\n");
' "$SRCCFG" "$REL/config.php" "$PREV" || fail "couldn't write the hub config"
php -l "$REL/config.php" >/dev/null || fail "generated config.php doesn't parse"

say "Permissions"
chown -R root:www-data "$REL"
chmod -R g+rX "$REL"
chown -R www-data:www-data "$REL/data" "$REL/uploads"
chmod 2775 "$REL/data" "$REL/uploads"
chmod 640 "$REL/config.php"

# Once the network has a shared uploads directory (created by
# upgrade-papers.sh), every new hub release serves it too — creatives and
# syndicated images resolve on every domain.
if [ -d /var/www/prairiepost-shared-uploads ] && [ ! -L "$REL/uploads" ]; then
  cp -an "$REL/uploads/." /var/www/prairiepost-shared-uploads/ 2>/dev/null
  rm -rf "$REL/uploads"
  ln -s /var/www/prairiepost-shared-uploads "$REL/uploads"
  chown -h www-data:www-data "$REL/uploads"
  echo "uploads -> shared"
fi

say "The edge kit — shared zones, headers and the anonymous microcache"
# Definitions live in http{} scope (harmless to unrelated vhosts on the box);
# they only take effect in server blocks that include the snippet.
mkdir -p /var/cache/nginx/civis /var/log/civis /etc/nginx/snippets
chown www-data:www-data /var/cache/nginx/civis /var/log/civis
cat > /etc/nginx/conf.d/civis-edge-zones.conf <<'ZONES'
# Civis Media edge kit (zones + maps) — written by deploy-civis.sh / harden-edge.sh.
limit_req_zone $binary_remote_addr zone=ppgeneral:10m rate=30r/s;
fastcgi_cache_path /var/cache/nginx/civis levels=1:2 keys_zone=ppcache:32m max_size=256m inactive=10m;
# Never cache for a browser holding a session, nor any admin/cron/api/ad path.
map $http_cookie $pp_skip_sess { default 0; ~*ppsession 1; }
map $request_uri $pp_skip_path { default 0; "~^/(admin|cron|api)([/?.]|$)" 1; "~^/ad([/?.]|$)" 1; }
ZONES
cat > /etc/nginx/snippets/civis-edge.conf <<'EDGE'
# Civis Media edge kit — security headers, per-IP request limiting, and a
# short microcache for anonymous readers (sessions start lazily app-side,
# so public GETs are cookie-free and cacheable). X-PP-Cache says HIT/MISS/
# BYPASS on PHP responses. Written by deploy-civis.sh / harden-edge.sh.
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()" always;
add_header Strict-Transport-Security "max-age=15552000" always;
add_header X-PP-Cache $upstream_cache_status always;

limit_req zone=ppgeneral burst=120 nodelay;
limit_req_status 429;

fastcgi_cache ppcache;
fastcgi_cache_key "$scheme$host$request_uri";
fastcgi_cache_methods GET HEAD;
fastcgi_cache_valid 200 301 60s;
fastcgi_cache_valid 404 10s;
fastcgi_cache_bypass $pp_skip_sess $pp_skip_path;
fastcgi_no_cache $pp_skip_sess $pp_skip_path;
fastcgi_cache_use_stale error timeout updating http_500 http_503;
fastcgi_cache_background_update on;
fastcgi_cache_lock on;
EDGE
cat > /etc/logrotate.d/civis <<'ROT'
/var/log/civis/*.log {
    weekly
    rotate 8
    compress
    missingok
    notifempty
}
ROT
echo "edge kit written (zones, snippet, logrotate)"

say "nginx vhost (HTTP first; certbot adds TLS after)"
VH=/etc/nginx/sites-available/civismedia
if [ -f "$VH" ]; then
  cp "$VH" "$VH.bak.$(date +%s)"
  echo "existing vhost backed up"
fi
cat > "$VH" <<NGINX
server {
    listen 80;
    listen [::]:80;
    server_name civismedia.ca www.civismedia.ca;
    root $REL;
    index index.php;
    include snippets/civis-edge.conf;

    # Protection — the .htaccess equivalents. Order matters.
    location ~ ^/(app|data)/            { deny all; }
    location ~ ^/uploads/.+\.(php|phtml|phar)\$ { deny all; }
    location ~ ^/(config\.php|config\.example\.php|router\.php)\$ { deny all; }

    # Pretty URLs.
    rewrite ^/story/([a-z0-9-]+)/?\$   /article.php?slug=\$1  last;
    rewrite ^/desk/([a-z0-9-]+)/?\$    /section.php?slug=\$1  last;
    rewrite ^/region/([a-z0-9-]+)/?\$  /region.php?slug=\$1   last;
    rewrite ^/author/([a-z0-9-]+)/?\$  /author.php?slug=\$1   last;
    rewrite ^/card/([a-z0-9-]+)\.png\$ /card.php?slug=\$1     last;
    rewrite ^/newsletter(/.*)?\$       /newsletter.php?path=\$1 last;
    rewrite ^/search/?\$               /search.php            last;
    rewrite ^/feed/?\$                 /feed.php              last;
    rewrite ^/sitemap\.xml\$           /sitemap.php           last;
    rewrite ^/subscribe/?\$            /subscribe.php         last;
    rewrite ^/contact/?\$              /contact.php           last;
    rewrite ^/api/monitor/?\$          /monitor-ingest.php    last;
    rewrite ^/api/media/?\$            /media-gateway.php     last;
    rewrite ^/ad/?\$                   /ad.php                last;
    rewrite ^/corrections/?\$          /corrections.php       last;

    location ~ \.php\$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:$FPM_SOCK;
        # The research desk's AI calls can legitimately run a couple of
        # minutes; without this nginx cuts them off at 60s.
        fastcgi_read_timeout 300;
    }
    location / { try_files \$uri \$uri/ =404; }
}
NGINX
ln -sf "$VH" /etc/nginx/sites-enabled/civismedia
if ! nginx -t; then
  rm -f /etc/nginx/sites-enabled/civismedia
  nginx -t
  fail "nginx config test failed — vhost disabled again, papers untouched"
fi
systemctl reload nginx
sleep 2   # let the new workers take over before the first checks hit them
echo "vhost live (HTTP)"

say "First boot — provisions the site row, migrates the shared database to the current schema"
BOOT=$(curl -s -H "Host: civismedia.ca" -o /tmp/civis_boot.html -w "%{http_code}" http://127.0.0.1/)
echo "first request: HTTP $BOOT"
grep -q "Clear communications" /tmp/civis_boot.html \
  && echo "PASS: brochure rendered" \
  || { echo "CHECK: brochure marker missing — first 200 chars follow"; head -c 200 /tmp/civis_boot.html; echo; }

say "Hub checks (over HTTP, before the TLS redirect exists)"
hcheck() { # path expect label
  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" -H "Host: civismedia.ca" "http://127.0.0.1$1")
  if [ "$code" = "$2" ]; then echo "PASS [$2] $3"; else echo "FAIL [got $code, want $2] $3"; fi
}
hcheck "/app/bootstrap.php" 403 "app/ blocked"
hcheck "/story/anything"    404 "stories 404 on the hub"
hcheck "/contact"           302 "contact endpoint answers (redirects GETs home)"
hcheck "/api/media?action=catalog" 401 "media gateway is routed and requires a bearer token"

say "Launch package (identity + brochure copy; never overwrites saved edits)"
( cd "$REL" && PP_SITE=civismedia php tools/seed-launch.php )
TITLE=$(curl -s -H "Host: civismedia.ca" http://127.0.0.1/ | grep -o "<title>[^<]*</title>" | head -1)
echo "front page now titles: ${TITLE:-<no title found>}"
echo "$TITLE" | grep -q "Civis Media" && echo "PASS: identity applied" || echo "CHECK: expected 'Civis Media' in the title"

say "The papers, untouched (over their own TLS)"
pcheck() { # domain
  local code
  code=$(curl -sk -o /dev/null -w "%{http_code}" --resolve "$1:443:127.0.0.1" "https://$1/")
  if [ "$code" = "200" ]; then echo "PASS $1 still serves"; else echo "FAIL $1 answered $code — investigate before anything else"; fi
}
pcheck prairiedispatch.ca
pcheck edmontonecho.com
pcheck westernwire.ca

say "TLS via certbot (uses the account that issued the papers' certs)"
if certbot --nginx -d civismedia.ca -d www.civismedia.ca -n --redirect; then
  CODE=$(curl -sk -o /dev/null -w "%{http_code}" --resolve "civismedia.ca:443:127.0.0.1" "https://civismedia.ca/")
  [ "$CODE" = "200" ] && echo "PASS: https://civismedia.ca serves the brochure" || echo "CHECK: HTTPS answered $CODE"
else
  echo "WARN: certbot failed — the site stays HTTP-only; re-run 'certbot --nginx -d civismedia.ca -d www.civismedia.ca -n --redirect' later"
fi

say "The hub's cron — monitoring hourly, agents every ten minutes, analytics nightly"
# Every job runs through the wrapper: outcome + output tail land in the ops
# ledger (hub dashboard + Ops page), full output in /var/log/civis/. The
# watch patrols every five minutes and files the network snapshot.
cat > /etc/cron.d/civismedia <<CRON
# Civis Media hub — written by deploy-civis.sh; repointed on every deploy.
17 * * * * www-data cd $REL && PP_SITE=civismedia php cron/run.php monitor >> /var/log/civis/monitor.log 2>&1
*/10 * * * * www-data cd $REL && PP_SITE=civismedia php cron/run.php agents >> /var/log/civis/agents.log 2>&1
43 2 * * * www-data cd $REL && PP_SITE=civismedia php cron/run.php analytics >> /var/log/civis/analytics.log 2>&1
*/5 * * * * www-data cd $REL && PP_SITE=civismedia php cron/run.php watch >> /var/log/civis/watch.log 2>&1
CRON
chmod 644 /etc/cron.d/civismedia
echo "cron installed: /etc/cron.d/civismedia -> $REL (monitor :17, agents */10, analytics 02:43, watch */5 — all via run.php)"

echo
echo "== done. Open https://civismedia.ca and https://civismedia.ca/admin =="
