#!/usr/bin/env bash
#
# Civis Media — Phase 1 deploy for the network's VPS.
# Follows the box's own convention: a fresh /var/www/prairiepost-<sha>
# release directory for the hub, its own nginx vhost, its own cert.
# Touches NOTHING the papers serve from. The only shared change is the
# database's additive v8 migration, which runs on the hub's first boot.
#
# Secrets never appear here: the database credentials are copied on the
# box, from the Prairie Dispatch's existing config.php.
#
# Run as root:  curl -fsSL <raw url> | bash
#
set -uo pipefail

REPO="FTFNAnalytics/prairiepost"
BRANCH="claude/master-dashboard-control-room-nr3mp4"
DOMAIN="civismedia.ca"
FPM_SOCK="/run/php/php8.3-fpm.sock"

say()  { echo; echo "== $*"; }
fail() { echo "FATAL: $*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || fail "run as root (the browser terminal is root already)"
command -v nginx >/dev/null || fail "nginx not found"
command -v php   >/dev/null || fail "php not found"
[ -S "$FPM_SOCK" ] || fail "php-fpm socket $FPM_SOCK not found"

say "Resolve the branch head"
SHA=$(curl -fsSL "https://api.github.com/repos/$REPO/branches/${BRANCH//\//%2F}" \
      | php -r '$d=json_decode(stream_get_contents(STDIN),true); echo substr($d["commit"]["sha"]??"",0,12);')
[ -n "$SHA" ] || SHA="civis-$(date +%Y%m%d%H%M)"
REL="/var/www/prairiepost-$SHA"
echo "release directory: $REL"

say "Fetch the release"
if [ -d "$REL" ]; then
  echo "already present — reusing (re-run friendly)"
else
  TMP=$(mktemp -d)
  curl -fsSL "https://codeload.github.com/$REPO/tar.gz/refs/heads/$BRANCH" -o "$TMP/rel.tgz" \
    || fail "couldn't download the branch tarball"
  tar -xzf "$TMP/rel.tgz" -C "$TMP" || fail "tarball didn't extract"
  INNER=$(find "$TMP" -maxdepth 1 -mindepth 1 -type d | head -1)
  [ -f "$INNER/app/bootstrap.php" ] || fail "extracted tree doesn't look like the app"
  mv "$INNER" "$REL"
  rm -rf "$TMP"
fi

say "Build the hub's config.php from the Dispatch's (credentials stay on this box)"
SRC=""
for d in /var/www/prairiepost-*; do
  [ -f "$d/config.php" ] || continue
  grep -q "'site_slug' => 'prairiedispatch'" "$d/config.php" && SRC="$d" && break
done
[ -n "$SRC" ] || fail "no existing config.php with site_slug prairiedispatch found to copy the db block from"
echo "config source: $SRC/config.php"
php -r '
$c = require $argv[1];
$c["site_slug"] = "civismedia";
$c["hub_slug"]  = "civismedia";   // the control room lives on this site
$c["site_url"]  = "https://civismedia.ca";
file_put_contents($argv[2], "<?php\n// Civis Media — the hub. Generated by deploy-civis.sh from the Dispatch config.\nreturn " . var_export($c, true) . ";\n");
' "$SRC/config.php" "$REL/config.php" || fail "couldn't write the hub config"
php -l "$REL/config.php" >/dev/null || fail "generated config.php doesn't parse"

say "Permissions"
chown -R root:www-data "$REL"
chmod -R g+rX "$REL"
chown -R www-data:www-data "$REL/data" "$REL/uploads"
chmod 2775 "$REL/data" "$REL/uploads"
chmod 640 "$REL/config.php"

# Once the network has a shared uploads directory (created by
# upgrade-papers.sh), every new hub release serves it too — creatives and
# syndicated images resolve on every domain.
if [ -d /var/www/prairiepost-shared-uploads ] && [ ! -L "$REL/uploads" ]; then
  cp -an "$REL/uploads/." /var/www/prairiepost-shared-uploads/ 2>/dev/null
  rm -rf "$REL/uploads"
  ln -s /var/www/prairiepost-shared-uploads "$REL/uploads"
  chown -h www-data:www-data "$REL/uploads"
  echo "uploads -> shared"
fi

say "nginx vhost (HTTP first; certbot adds TLS after)"
VH=/etc/nginx/sites-available/civismedia
if [ -f "$VH" ]; then
  cp "$VH" "$VH.bak.$(date +%s)"
  echo "existing vhost backed up"
fi
cat > "$VH" <<NGINX
server {
    listen 80;
    listen [::]:80;
    server_name civismedia.ca www.civismedia.ca;
    root $REL;
    index index.php;

    # Protection — the .htaccess equivalents. Order matters.
    location ~ ^/(app|data)/            { deny all; }
    location ~ ^/uploads/.+\.(php|phtml|phar)\$ { deny all; }
    location ~ ^/(config\.php|config\.example\.php|router\.php)\$ { deny all; }

    # Pretty URLs.
    rewrite ^/story/([a-z0-9-]+)/?\$   /article.php?slug=\$1  last;
    rewrite ^/desk/([a-z0-9-]+)/?\$    /section.php?slug=\$1  last;
    rewrite ^/region/([a-z0-9-]+)/?\$  /region.php?slug=\$1   last;
    rewrite ^/author/([a-z0-9-]+)/?\$  /author.php?slug=\$1   last;
    rewrite ^/card/([a-z0-9-]+)\.png\$ /card.php?slug=\$1     last;
    rewrite ^/newsletter(/.*)?\$       /newsletter.php?path=\$1 last;
    rewrite ^/search/?\$               /search.php            last;
    rewrite ^/feed/?\$                 /feed.php              last;
    rewrite ^/sitemap\.xml\$           /sitemap.php           last;
    rewrite ^/subscribe/?\$            /subscribe.php         last;
    rewrite ^/contact/?\$              /contact.php           last;
    rewrite ^/ad/?\$                   /ad.php                last;
    rewrite ^/corrections/?\$          /corrections.php       last;

    location ~ \.php\$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:$FPM_SOCK;
    }
    location / { try_files \$uri \$uri/ =404; }
}
NGINX
ln -sf "$VH" /etc/nginx/sites-enabled/civismedia
if ! nginx -t; then
  rm -f /etc/nginx/sites-enabled/civismedia
  nginx -t
  fail "nginx config test failed — vhost disabled again, papers untouched"
fi
systemctl reload nginx
sleep 2   # let the new workers take over before the first checks hit them
echo "vhost live (HTTP)"

say "First boot — provisions the site row, migrates the shared database to v8"
BOOT=$(curl -s -H "Host: civismedia.ca" -o /tmp/civis_boot.html -w "%{http_code}" http://127.0.0.1/)
echo "first request: HTTP $BOOT"
grep -q "Clear communications" /tmp/civis_boot.html \
  && echo "PASS: brochure rendered" \
  || { echo "CHECK: brochure marker missing — first 200 chars follow"; head -c 200 /tmp/civis_boot.html; echo; }

say "Hub checks (over HTTP, before the TLS redirect exists)"
hcheck() { # path expect label
  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" -H "Host: civismedia.ca" "http://127.0.0.1$1")
  if [ "$code" = "$2" ]; then echo "PASS [$2] $3"; else echo "FAIL [got $code, want $2] $3"; fi
}
hcheck "/app/bootstrap.php" 403 "app/ blocked"
hcheck "/story/anything"    404 "stories 404 on the hub"
hcheck "/contact"           302 "contact endpoint answers (redirects GETs home)"

say "Launch package (identity + brochure copy; never overwrites saved edits)"
( cd "$REL" && PP_SITE=civismedia php tools/seed-launch.php )
TITLE=$(curl -s -H "Host: civismedia.ca" http://127.0.0.1/ | grep -o "<title>[^<]*</title>" | head -1)
echo "front page now titles: ${TITLE:-<no title found>}"
echo "$TITLE" | grep -q "Civis Media" && echo "PASS: identity applied" || echo "CHECK: expected 'Civis Media' in the title"

say "The papers, untouched (over their own TLS)"
pcheck() { # domain
  local code
  code=$(curl -sk -o /dev/null -w "%{http_code}" --resolve "$1:443:127.0.0.1" "https://$1/")
  if [ "$code" = "200" ]; then echo "PASS $1 still serves"; else echo "FAIL $1 answered $code — investigate before anything else"; fi
}
pcheck prairiedispatch.ca
pcheck edmontonecho.com
pcheck westernwire.ca

say "TLS via certbot (uses the account that issued the papers' certs)"
if certbot --nginx -d civismedia.ca -d www.civismedia.ca -n --redirect; then
  CODE=$(curl -sk -o /dev/null -w "%{http_code}" --resolve "civismedia.ca:443:127.0.0.1" "https://civismedia.ca/")
  [ "$CODE" = "200" ] && echo "PASS: https://civismedia.ca serves the brochure" || echo "CHECK: HTTPS answered $CODE"
else
  echo "WARN: certbot failed — the site stays HTTP-only; re-run 'certbot --nginx -d civismedia.ca -d www.civismedia.ca -n --redirect' later"
fi

echo
echo "== done. Open https://civismedia.ca and https://civismedia.ca/admin =="
