#!/usr/bin/env bash
#
# Store (or rotate) the research desk's Anthropic API key in the HUB's
# config.php — the release the civismedia vhost serves right now.
#
# The key is prompted with echo off and read from the terminal directly, so
# it never appears on screen, in shell history, in this script, or in any
# log. It is written only into config.php (mode 640), which is where the
# desk reads it from; it never enters the database or the repository.
#
# Only the hub's config is ever evaluated, and only after a grep proves it
# is the static file deploy-civis.sh generated (literal civismedia slug) —
# never a paper's host-mapped config.
#
# Run as root:  curl -fsSL <raw url> | bash
#
set -uo pipefail

fail() { echo "FATAL: $*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || fail "run as root"

VH=$(readlink -f /etc/nginx/sites-enabled/civismedia 2>/dev/null) || fail "no civismedia vhost is enabled — deploy the hub first"
[ -f "$VH" ] || fail "civismedia vhost file missing"
ROOT=$(grep -Eo 'root[[:space:]]+/var/www/prairiepost-[A-Za-z0-9._-]+' "$VH" | head -1 | awk '{print $2}')
[ -n "$ROOT" ] && [ -d "$ROOT" ] || fail "couldn't resolve the hub's release directory from the vhost"
CFG="$ROOT/config.php"
[ -f "$CFG" ] || fail "no config.php at $ROOT"
grep -q "'site_slug' => 'civismedia'" "$CFG" \
  || fail "$CFG doesn't look like the generated hub config (no literal civismedia slug) — not touching it"
echo "hub config: $CFG"

printf 'Paste the Anthropic API key (input is hidden), then press Enter: '
IFS= read -rs KEY < /dev/tty
echo
KEY=$(printf '%s' "$KEY" | tr -d '[:space:]')
[ -n "$KEY" ] || fail "empty key — nothing changed"
case "$KEY" in
  sk-ant-*) : ;;
  *) echo "WARN: Anthropic keys normally start with sk-ant- — storing what you pasted anyway" ;;
esac

cp "$CFG" "$CFG.bak.$(date +%s)"

# The key travels via the environment, not argv, so it is never ps-visible.
KEY="$KEY" php -r '
$f = $argv[1];
$c = require $f;                 // static literal — generated by deploy-civis.sh
if (!is_array($c)) { fwrite(STDERR, "config did not return an array\n"); exit(1); }
$c["anthropic_api_key"] = (string) getenv("KEY");
file_put_contents($f, "<?php\n// Civis Media — the hub. Generated by deploy-civis.sh from the Dispatch config.\nreturn " . var_export($c, true) . ";\n");
' "$CFG" || fail "couldn't write the key — config.php is unchanged (backup kept either way)"

php -l "$CFG" >/dev/null || fail "config.php no longer parses — restore the newest $CFG.bak.* file"
chown root:www-data "$CFG"
chmod 640 "$CFG"

php -r '$c = require $argv[1]; exit(empty($c["anthropic_api_key"]) ? 1 : 0);' "$CFG" \
  && echo "PASS: key stored (mode 640, root:www-data). It will carry forward automatically on future deploys." \
  || fail "the key didn't land — restore the backup and retry"

CODE=$(curl -sk -o /dev/null -w "%{http_code}" --resolve "civismedia.ca:443:127.0.0.1" "https://civismedia.ca/")
echo "hub front page: HTTP $CODE"
echo
echo "Now sign in at https://civismedia.ca/admin → Research desk — it should no longer say 'Not connected'."
