#!/usr/bin/env bash
#
# Upgrade every paper on the network box to the branch's current release.
# Follows the box's own convention — a fresh release directory per paper —
# and adds the one structural fix the network has been owed: a single
# shared /uploads directory, symlinked into every release, so campaign
# creatives and syndicated story images resolve on every domain.
#
# Per paper: new /var/www/prairiepost-<sha>-<slug> from the branch tarball,
# config.php carried over (regenerated with hub_slug added; credentials
# never leave the box), uploads merged into the shared directory, vhost
# repointed. Gated: nginx -t failure restores every vhost and aborts; a
# paper that fails its post-reload check gets its vhost restored alone.
#
# Run as root:  curl -fsSL <raw url> | bash
#
set -uo pipefail

REPO="FTFNAnalytics/prairiepost"
BRANCH="claude/master-dashboard-control-room-nr3mp4"
SHARED_UP="/var/www/prairiepost-shared-uploads"
STAMP=$(date +%s)

say()  { echo; echo "== $*"; }
fail() { echo "FATAL: $*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || fail "run as root"
command -v nginx >/dev/null || fail "nginx not found"

say "Resolve the branch head"
SHA=$(curl -fsSL "https://api.github.com/repos/$REPO/branches/${BRANCH//\//%2F}" \
      | php -r '$d=json_decode(stream_get_contents(STDIN),true); echo substr($d["commit"]["sha"]??"",0,12);')
[ -n "$SHA" ] || fail "couldn't resolve the branch head"
echo "release: $SHA"

say "Fetch the release template once"
TPL=$(mktemp -d)/tpl
mkdir -p "$(dirname "$TPL")"
TMP=$(mktemp -d)
curl -fsSL "https://codeload.github.com/$REPO/tar.gz/refs/heads/$BRANCH" -o "$TMP/rel.tgz" || fail "tarball download failed"
tar -xzf "$TMP/rel.tgz" -C "$TMP" || fail "tarball didn't extract"
INNER=$(find "$TMP" -maxdepth 1 -mindepth 1 -type d | head -1)
[ -f "$INNER/app/bootstrap.php" ] || fail "extracted tree doesn't look like the app"
mv "$INNER" "$TPL"

say "Build the shared uploads directory (merging every release's images)"
mkdir -p "$SHARED_UP"
for d in /var/www/prairiepost-*/; do
  d=${d%/}
  [ "$d" = "$SHARED_UP" ] && continue
  if [ -d "$d/uploads" ] && [ ! -L "$d/uploads" ]; then
    cp -an "$d/uploads/." "$SHARED_UP/" 2>/dev/null
  fi
done
chown -R www-data:www-data "$SHARED_UP"
chmod 2775 "$SHARED_UP"
echo "shared uploads: $(du -sh "$SHARED_UP" 2>/dev/null | cut -f1) at $SHARED_UP"

say "Find the papers behind nginx"
declare -a BACKUPS=()
declare -a REPORT=()
UPGRADED=0
for link in /etc/nginx/sites-enabled/*; do
  base=$(basename "$link")
  case "$base" in civismedia|cies|README|default) continue ;; esac
  VH=$(readlink -f "$link")
  [ -f "$VH" ] || continue
  OLD=$(grep -Eo 'root[[:space:]]+/var/www/prairiepost-[A-Za-z0-9._-]+' "$VH" | head -1 | awk '{print $2}')
  [ -n "$OLD" ] && [ -d "$OLD" ] || { echo "-- $base: no prairiepost root, skipped"; continue; }
  [ -f "$OLD/config.php" ] || { echo "-- $base: no config.php at $OLD, skipped"; continue; }
  DOMAIN=$(grep -Eo 'server_name[[:space:]]+[^;]+' "$VH" | head -1 | awk '{print $2}')

  SLUG=$(php -r '$c = require $argv[1]; echo is_string($c["site_slug"] ?? null) ? $c["site_slug"] : "";' "$OLD/config.php")
  [ -n "$SLUG" ] || { echo "-- $base: couldn't read site_slug (host-mapped config?), skipped"; continue; }
  NEW="/var/www/prairiepost-$SHA-$SLUG"

  if [ "$OLD" = "$NEW" ]; then
    echo "-- $base ($SLUG): already on $SHA"
    continue
  fi

  echo "-- $base ($SLUG): $OLD -> $NEW"
  if [ ! -d "$NEW" ]; then
    cp -a "$TPL" "$NEW" || { echo "   copy failed, skipped"; continue; }
  fi

  # Config: same values plus the hub key, regenerated on the box.
  php -r '
  $c = require $argv[1];
  $c["hub_slug"] = $c["hub_slug"] ?? "civismedia";
  file_put_contents($argv[2], "<?php\n// Regenerated by upgrade-papers.sh from the previous release'\''s config.\nreturn " . var_export($c, true) . ";\n");
  ' "$OLD/config.php" "$NEW/config.php" || { echo "   config rewrite failed, skipped"; continue; }
  php -l "$NEW/config.php" >/dev/null || { echo "   config doesn't parse, skipped"; continue; }

  # Uploads become the shared directory; data stays per-release (cache only).
  rm -rf "$NEW/uploads"
  ln -s "$SHARED_UP" "$NEW/uploads"
  chown -R root:www-data "$NEW"
  chmod -R g+rX "$NEW"
  chown -h www-data:www-data "$NEW/uploads"
  chown -R www-data:www-data "$NEW/data"
  chmod 2775 "$NEW/data"
  chmod 640 "$NEW/config.php"

  cp "$VH" "$VH.bak.$STAMP"
  BACKUPS+=("$VH")
  sed -i "s|root[[:space:]]\+$OLD;|root $NEW;|" "$VH"
  grep -q "root $NEW;" "$VH" || { cp "$VH.bak.$STAMP" "$VH"; echo "   vhost rewrite failed, restored, skipped"; continue; }

  # Crons follow the release they call.
  for cf in /etc/cron.d/*; do
    [ -f "$cf" ] || continue
    if grep -q "$OLD" "$cf"; then
      cp "$cf" "$cf.bak.$STAMP"
      sed -i "s|$OLD|$NEW|g" "$cf"
      echo "   cron updated: $(basename "$cf")"
    fi
  done

  REPORT+=("$base|$DOMAIN|$OLD|$NEW")
  UPGRADED=$((UPGRADED + 1))
done

[ "$UPGRADED" -gt 0 ] || { echo; echo "Nothing to upgrade — every paper is already on $SHA."; exit 0; }

say "Point the hub's release at the shared uploads too"
HUBVH=$(readlink -f /etc/nginx/sites-enabled/civismedia 2>/dev/null || true)
if [ -n "$HUBVH" ] && [ -f "$HUBVH" ]; then
  HUBROOT=$(grep -Eo 'root[[:space:]]+/var/www/prairiepost-[A-Za-z0-9._-]+' "$HUBVH" | head -1 | awk '{print $2}')
  if [ -n "$HUBROOT" ] && [ -d "$HUBROOT/uploads" ] && [ ! -L "$HUBROOT/uploads" ]; then
    cp -an "$HUBROOT/uploads/." "$SHARED_UP/" 2>/dev/null
    rm -rf "$HUBROOT/uploads"
    ln -s "$SHARED_UP" "$HUBROOT/uploads"
    chown -h www-data:www-data "$HUBROOT/uploads"
    echo "hub uploads now shared"
  else
    echo "hub uploads already shared (or hub root not found)"
  fi
fi

say "nginx config test + reload"
if ! nginx -t; then
  for VH in "${BACKUPS[@]}"; do cp "$VH.bak.$STAMP" "$VH"; done
  nginx -t
  fail "nginx test failed — every vhost restored, nothing changed"
fi
systemctl reload nginx
sleep 2

say "Verify every upgraded paper"
FAILED=0
for entry in "${REPORT[@]}"; do
  IFS='|' read -r base domain old new <<< "$entry"
  code=$(curl -sk -m 15 -o /tmp/up_check.html -w "%{http_code}" --resolve "$domain:443:127.0.0.1" "https://$domain/")
  title=$(grep -o "<title>[^<]*</title>" /tmp/up_check.html | head -1)
  if [ "$code" = "200" ] && [ -n "$title" ]; then
    echo "PASS $domain -> $title"
  else
    echo "FAIL $domain answered $code — restoring its previous release"
    VH=$(readlink -f "/etc/nginx/sites-enabled/$base")
    cp "$VH.bak.$STAMP" "$VH"
    FAILED=$((FAILED + 1))
  fi
done
if [ "$FAILED" -gt 0 ]; then
  nginx -t && systemctl reload nginx
  echo "WARN: $FAILED paper(s) restored to their previous release — send the output back for a look."
else
  echo "All $UPGRADED paper(s) upgraded to $SHA."
fi

say "Done"
echo "Old release directories are untouched on disk — rollback for any paper is:"
echo "  cp <its vhost>.bak.$STAMP <its vhost> && nginx -t && systemctl reload nginx"
